services:
  cache:
    image: redis:7-alpine
    networks:
      - internal
    healthcheck:
      test: "redis-cli ping | grep PONG"
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 3
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 750M
          cpus: '0.75'
        reservations:
          memory: 10MB
          cpus: '0.05'

  db:
    image: postgres:15-bookworm
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD:
      POSTGRES_DB: survey
    healthcheck:
      test: pg_isready
      interval: 15s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 3
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 25MB
          cpus: '0.10'

  ohmyform_app:
    image: ohmyform/ohmyform
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL:
      ADMIN_PASSWORD:
      DATABASE_DRIVER: postgres
      DATABASE_URL: "postgres://survey:$POSTGRES_PASSWORD@db:5432/survey"
      MAILER_URL:
      MAILER_FROM:
      SIGNUP_DISABLED: "TRUE"
      SECRET_KEY:
      NODE_ENV: production
      REDIS_URL: "redis://cache:6379"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ohmyform_external"
      - "traefik.http.routers.ohmyform.entrypoints=web,websecure"
      - "traefik.http.routers.ohmyform.rule=Host(`survey.teknologiumum.com`)"
      - "traefik.http.routers.ohmyform.priority=1"
      - "traefik.http.routers.ohmyform.tls.certresolver=tlsresolver"
      - "traefik.http.routers.ohmyform.middlewares=ohmyform-header,ohmyform-rate,ohmyform-redirectscheme"
      - "traefik.http.services.ohmyform.loadbalancer.server.port=3000"
      - "traefik.http.services.ohmyform.loadbalancer.server.scheme=http"
      - "traefik.http.services.ohmyform.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.ohmyform.loadbalancer.healthcheck.path=/"
      - "traefik.http.middlewares.ohmyform-rate.ratelimit.average=100"
      - "traefik.http.middlewares.ohmyform-rate.ratelimit.burst=20"
      - "traefik.http.middlewares.ohmyform-rate.ratelimit.period=1s"
      - "traefik.http.middlewares.ohmyform-header.headers.accesscontrolallowmethods=GET,OPTIONS"
      - "traefik.http.middlewares.ohmyform-header.headers.accesscontrolalloworiginlist=https://survey.teknologiumum.com"
      - "traefik.http.middlewares.ohmyform-header.headers.accesscontrolmaxage=604800"
      - "traefik.http.middlewares.ohmyform-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.ohmyform-header.headers.frameDeny=true"
      - "traefik.http.middlewares.ohmyform-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.ohmyform-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.ohmyform-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.ohmyform-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.ohmyform-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.ohmyform-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.ohmyform-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ohmyform-redirectscheme.redirectscheme.permanent=true"
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    healthcheck:
      test: "wget -q --spider localhost:3000 || exit 1"
      interval: 30s
      timeout: 20s
      retries: 10
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 500MB
          cpus: '0.75'
        reservations:
          memory: 25MB
          cpus: '0.10'
    networks:
      - ohmyform_internal
      - ohmyform_external
    volumes:
      - application-data:/data

volumes:
  application-data:
  database-data:

networks:
  internal:
    ipam:
      config:
        - subnet: 172.16.22.144/28
    external: false
  ohmyform_external:
    ipam:
      config:
        - subnet: 172.16.21.128/28
    external: true
