services:
  postgres:
    image: postgres:15.3-bookworm
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      TZ: UTC
    platform: linux/amd64
    healthcheck:
      test: pg_isready
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 2GB
          cpus: '2'
        reservations:
          memory: 50MB
          cpus: '0.10'
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 3

  postgres-exporter:
    hostname: captcha.postgres-exporter
    image: quay.io/prometheuscommunity/postgres-exporter
    platform: linux/amd64
    environment:
      DATA_SOURCE_NAME: "${POSTGRES_URL}"
    networks:
      - monitoring
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 200MB
          cpus: '1'
        reservations:
          memory: 50MB
          cpus: '0.10'
    logging:
      driver: local
      options:
        max-size: 1M
        max-file: 3

  application:
    image: ghcr.io/teknologi-umum/captcha:edge
    environment:
      ENVIRONMENT: production
      BOT_TOKEN:
      SENTRY_DSN:
      DATABASE_URL:
      POSTGRES_URL:
      MONGO_URL:
      TZ: UTC
      TEKNUM_ID:
      HOME_GROUP_ID:
      ADMIN_ID:
      ADMIN_IDS:
      FEATURE_FLAG_DUKUN: true
      FEATURE_FLAG_BADWORDS_INSERTION: true
      FEATURE_FLAG_UNDER_ATTACK: true
      FEATURE_FLAG_ANALYTICS: true
      FEATURE_FLAG_REMINDER: true
      HTTP_PORT: 8080
      UNDER_ATTACK__DATASTORE_PROVIDER: postgres
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=captcha"
      - "traefik.http.routers.captcha_bot.entrypoints=web,websecure"
      - "traefik.http.routers.captcha_bot.rule=Host(`captcha.teknologiumum.com`)"
      - "traefik.http.routers.captcha_bot.tls.certresolver=tlsresolver"
      - "traefik.http.routers.captcha_bot.middlewares=captcha_bot-header,captcha_bot-rate,captcha_bot-redirectscheme"
      - "traefik.http.services.captcha_bot.loadbalancer.server.port=8080"
      - "traefik.http.services.captcha_bot.loadbalancer.server.scheme=http"
      - "traefik.http.services.captcha_bot.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.captcha_bot.loadbalancer.healthcheck.path=/"
      - "traefik.http.middlewares.captcha_bot-rate.ratelimit.average=100"
      - "traefik.http.middlewares.captcha_bot-rate.ratelimit.burst=20"
      - "traefik.http.middlewares.captcha_bot-rate.ratelimit.period=1m"
      - "traefik.http.middlewares.captcha_bot-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.captcha_bot-header.headers.frameDeny=true"
      - "traefik.http.middlewares.captcha_bot-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.captcha_bot-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.captcha_bot-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.captcha_bot-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.captcha_bot-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.captcha_bot-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.captcha_bot-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.captcha_bot-redirectscheme.redirectscheme.permanent=true"
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    healthcheck:
      test: curl -f http://application:8080 || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 500MB
          cpus: '1'
        reservations:
          memory: 25MB
          cpus: '0.10'
    networks:
      - captcha
      - internal
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 100M
        max-file: 3

volumes:
  postgres-data:

networks:
  captcha:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.16.21.80/28
  internal:
    ipam:
      config:
        - subnet: 172.16.22.0/28
  monitoring:
    external: true
