services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=public-web"
      - "traefik.http.routers.umami.entrypoints=web,websecure"
      - "traefik.http.routers.umami.rule=Host(`analytics.teknologiumum.com`)"
      - "traefik.http.routers.umami.tls.certresolver=tlsresolver"
      - "traefik.http.routers.umami.middlewares=umami-header,umami-rate,umami-redirectscheme"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"
      - "traefik.http.services.umami.loadbalancer.server.scheme=http"
      - "traefik.http.services.umami.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.umami.loadbalancer.healthcheck.path=/api/heartbeat"
      - "traefik.http.middlewares.umami-rate.ratelimit.average=200"
      - "traefik.http.middlewares.umami-rate.ratelimit.burst=100"
      - "traefik.http.middlewares.umami-rate.ratelimit.period=1s"
      - "traefik.http.middlewares.umami-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.umami-header.headers.frameDeny=true"
      - "traefik.http.middlewares.umami-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.umami-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.umami-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.umami-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.umami-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.umami-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.umami-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.umami-redirectscheme.redirectscheme.permanent=true"
    networks:
      - public-web
      - umami-internal
    environment:
      DATABASE_URL:
      DATABASE_TYPE: postgresql
      APP_SECRET:
      DISABLE_BOT_CHECK: 1
      DISABLE_UPDATES: 1
      DISABLE_TELEMETRY: 1
      REMOVE_TRAILING_SLASH: 1
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 30s
      timeout: 20s
      retries: 5
    logging:
      driver: local
      options:
        max-size: 10M
        max-file: 3

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - umami-internal
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 20s
      retries: 5
    logging:
      driver: local
      options:
        max-size: 10M
        max-file: 3

volumes:
  umami-db-data:
    external: true

networks:
  umami-internal:
  public-web:
    external: true
