services:
  bagetter:
    image: bagetter/bagetter:latest
    environment:
      Mirror__Enabled: true
      Mirror__PackageSource: "https://api.nuget.org/v3/index.json"
      ApiKey:
      PackageDeletionBehavior: "HardDelete"
    network_mode: host
    command: --urls http://0.0.0.0:5000
    volumes:
      - bagetter-storage:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=public-web"
      - "traefik.http.routers.bagetter.entrypoints=web,websecure"
      - "traefik.http.routers.bagetter.rule=Host(`nuget.teknologiumum.com`)"
      - "traefik.http.routers.bagetter.tls.certresolver=tlsresolver"
      - "traefik.http.routers.bagetter.middlewares=bagetter-header,bagetter-redirectscheme"
      - "traefik.http.services.bagetter.loadbalancer.server.port=5000"
      - "traefik.http.services.bagetter.loadbalancer.server.scheme=http"
      - "traefik.http.services.bagetter.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.middlewares.bagetter-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.bagetter-header.headers.frameDeny=true"
      - "traefik.http.middlewares.bagetter-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.bagetter-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.bagetter-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.bagetter-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.bagetter-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.bagetter-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.bagetter-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.bagetter-redirectscheme.redirectscheme.permanent=true"
    networks:
      - public-web
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
    logging:
      driver: local
      options:
        max-size: 10M
        max-file: 3

volumes:
  bagetter-storage:
    external: true

networks:
  public-web:
    external: true
