services:
  verdaccio:
    image: verdaccio/verdaccio:5
    volumes:
      - verdaccio-storage:/verdaccio/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verdaccio.entrypoints=web,websecure"
      - "traefik.http.routers.verdaccio.rule=Host(`npmjs.teknologiumum.com`)"
      - "traefik.http.routers.verdaccio.tls.certresolver=tlsresolver"
      - "traefik.http.routers.verdaccio.middlewares=verdaccio-header,verdaccio-redirectscheme"
      - "traefik.http.services.verdaccio.loadbalancer.server.port=4873"
      - "traefik.http.services.verdaccio.loadbalancer.server.scheme=http"
      - "traefik.http.services.verdaccio.loadbalancer.healthcheck.interval=120s"
      - "traefik.http.services.verdaccio.loadbalancer.healthcheck.path=/"
      - "traefik.http.middlewares.verdaccio-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.verdaccio-header.headers.frameDeny=true"
      - "traefik.http.middlewares.verdaccio-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.verdaccio-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.verdaccio-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.verdaccio-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.verdaccio-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.verdaccio-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.verdaccio-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.verdaccio-redirectscheme.redirectscheme.permanent=true"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - public-web
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 3

volumes:
  verdaccio-storage:
    external: true

networks:
  public-web:
    external: true
