services:
  bot:
    image: ghcr.io/teknologi-umum/bot:edge
    environment:
      NODE_ENV: production
      MONGO_URL:
      BOT_TOKEN:
      FINNHUB_KEY:
      SENTRY_DSN:
      HOME_GROUP_ID:
      LOGTAIL_TOKEN:
      REDIS_URL:
      PESTO_TOKEN:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 300MB
          cpus: '0.75'
        reservations:
          memory: 50MB
          cpus: '0.10'
