services:
  gold:
    # Soon
    # image: ghcr.io/teknologi-umum/gold:edge 
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gold"
      - "traefik.http.routers.gold.entrypoints=web,websecure"
      - "traefik.http.routers.gold.rule=Host(`gold.teknologiumum.com`)"
      - "traefik.http.routers.gold.tls.certresolver=tlsresolver"
      - "traefik.http.routers.gold.middlewares=gold-header,gold-rate,gold-redirectscheme"
      - "traefik.http.services.gold.loadbalancer.server.port=7390"
      - "traefik.http.services.gold.loadbalancer.server.scheme=http"
      - "traefik.http.services.gold.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.gold.loadbalancer.healthcheck.path=/_ping"
      - "traefik.http.middlewares.gold-rate.ratelimit.average=200"
      - "traefik.http.middlewares.gold-rate.ratelimit.burst=100"
      - "traefik.http.middlewares.gold-rate.ratelimit.period=1s"
      - "traefik.http.middlewares.gold-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.gold-header.headers.frameDeny=true"
      - "traefik.http.middlewares.gold-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.gold-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.gold-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.gold-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.gold-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.gold-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.gold-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.gold-redirectscheme.redirectscheme.permanent=true"
      # - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    healthcheck:
      test: curl -f http://localhost:7390/_ping || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 500MB
          cpus: '1'
        reservations:
          memory: 10M
          cpus: '0.05'
    networks:
      - gold
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 1

networks:
  gold:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.16.20.0/28
