x-defaults:
  &defaults
  ENVIRONMENT: production

services:
  pesto-landing:
    image: ghcr.io/teknologi-umum/pesto-landing:edge
    environment:
      <<: [ *defaults ]
      PORT: 3000
      SENTRY_DSN: ${LANDING_SENTRY_DSN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-web"
      - "traefik.http.routers.pesto_landing.entrypoints=web,websecure"
      - "traefik.http.routers.pesto_landing.rule=Host(`pesto.teknologiumum.com`)"
      - "traefik.http.routers.pesto_landing.priority=1"
      - "traefik.http.routers.pesto_landing.tls.certresolver=tlsresolver"
      - "traefik.http.routers.pesto_landing.middlewares=pesto_landing-header,pesto_landing-rate,pesto_landing-redirectscheme"
      - "traefik.http.services.pesto_landing.loadbalancer.server.port=3000"
      - "traefik.http.services.pesto_landing.loadbalancer.server.scheme=http"
      - "traefik.http.services.pesto_landing.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.pesto_landing.loadbalancer.healthcheck.path=/"
      - "traefik.http.middlewares.pesto_landing-rate.ratelimit.average=100"
      - "traefik.http.middlewares.pesto_landing-rate.ratelimit.burst=20"
      - "traefik.http.middlewares.pesto_landing-rate.ratelimit.period=1s"
      - "traefik.http.middlewares.pesto_landing-header.headers.accesscontrolallowmethods=GET,OPTIONS"
      - "traefik.http.middlewares.pesto_landing-header.headers.accesscontrolalloworiginlist=https://teknologiumum.com"
      - "traefik.http.middlewares.pesto_landing-header.headers.accesscontrolmaxage=604800"
      - "traefik.http.middlewares.pesto_landing-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.pesto_landing-header.headers.frameDeny=true"
      - "traefik.http.middlewares.pesto_landing-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.pesto_landing-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.pesto_landing-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.pesto_landing-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.pesto_landing-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.pesto_landing-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.pesto_landing-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.pesto_landing-redirectscheme.redirectscheme.permanent=true"
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    healthcheck:
      test: "curl -f http://localhost:3000/ || exit 1"
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 350MB
          cpus: '0.75'
        reservations:
          memory: 25MB
          cpus: '0.10'
    networks:
      - public-web

  db:
    image: ghcr.io/teknologi-umum/pesto-redis:edge
    container_name: db
    platform: linux/amd64
    healthcheck:
      test: "redis-cli ping | grep PONG"
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 60s
      resources:
        limits:
          memory: 2GB
          cpus: '1'
        reservations:
          memory: 100MB
          cpus: '0.25'
    networks:
      - pesto-internal
    volumes:
      - ../redis:/data
  
  pesto-auth:
    image: ghcr.io/teknologi-umum/pesto-auth:edge
    environment:
      <<: [ *defaults ]
      PORT: 3000
      SENTRY_DSN: ${AUTH_SENTRY_DSN}
      REDIS_URL: redis://@db:6379/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-web"
      - "traefik.http.routers.pesto_auth.entrypoints=web,websecure"
      - "traefik.http.routers.pesto_auth.middlewares=pesto_auth-error,pesto_auth-header,pesto_auth-rate"
      - "traefik.http.services.pesto_auth.loadbalancer.server.port=3000"
      - "traefik.http.services.pesto_auth.loadbalancer.server.scheme=http"
      - "traefik.http.services.pesto_auth.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.pesto_auth.loadbalancer.healthcheck.path=/healthz"
      - "traefik.http.middlewares.pesto_auth-error.errors.status=500-599"
      - "traefik.http.middlewares.pesto_auth-error.errors.service=pesto_landing@docker"
      - "traefik.http.middlewares.pesto_auth-error.errors.query=/500"
      - "traefik.http.middlewares.pesto_auth-rate.ratelimit.average=20"
      - "traefik.http.middlewares.pesto_auth-rate.ratelimit.burst=5"
      - "traefik.http.middlewares.pesto_auth-rate.ratelimit.period=1s"
      - "traefik.http.middlewares.pesto_auth-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.pesto_auth-header.headers.frameDeny=true"
      - "traefik.http.middlewares.pesto_auth-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.pesto_auth-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.pesto_auth-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.pesto_auth-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.pesto_auth-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.pesto_auth-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    healthcheck:
      test: "curl -f http://localhost:3000/healthz || exit 1"
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 500MB
          cpus: '0.75'
        reservations:
          memory: 25MB
          cpus: '0.10'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public-web
      - pesto-internal

  pesto-rce:
    image: ghcr.io/teknologi-umum/pesto-rce:edge
    environment:
      <<: [ *defaults ]
      PORT: 50051
      SENTRY_DSN: ${RCE_SENTRY_DSN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-web"
      - "traefik.http.routers.pesto_rce.entrypoints=web,websecure"
      - "traefik.http.routers.pesto_rce.rule=Host(`pesto.teknologiumum.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.pesto_rce.priority=3"
      - "traefik.http.routers.pesto_rce.tls.certresolver=tlsresolver"
      - "traefik.http.routers.pesto_rce.middlewares=pesto_rce-auth,pesto_rce-error,pesto_rce-header,pesto_rce-rate,pesto_rce-redirectscheme"
      - "traefik.http.services.pesto_rce.loadbalancer.server.port=50051"
      - "traefik.http.services.pesto_rce.loadbalancer.server.scheme=http"
      - "traefik.http.services.pesto_rce.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.pesto_rce.loadbalancer.healthcheck.path=/healthz"
      - "traefik.http.middlewares.pesto_rce-auth.forwardauth.address=http://pesto-auth:3000/"
      - "traefik.http.middlewares.pesto_rce-auth.forwardauth.authRequestHeaders=Accept,X-Pesto-Token,Referer,Origin"
      - "traefik.http.middlewares.pesto_rce-auth.forwardauth.authResponseHeaders=Sentry-Trace,Baggage"
      - "traefik.http.middlewares.pesto_rce-auth.forwardauth.tls.insecureSkipVerify=true"
      - "traefik.http.middlewares.pesto_rce-error.errors.status=500-599"
      - "traefik.http.middlewares.pesto_rce-error.errors.service=pesto_landing@docker"
      - "traefik.http.middlewares.pesto_rce-error.errors.query=/500"
      - "traefik.http.middlewares.pesto_rce-rate.ratelimit.average=60"
      - "traefik.http.middlewares.pesto_rce-rate.ratelimit.burst=5"
      - "traefik.http.middlewares.pesto_rce-rate.ratelimit.period=1m"
      - "traefik.http.middlewares.pesto_rce-header.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.pesto_rce-header.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.pesto_rce-header.headers.accesscontrolmaxage=604800"
      - "traefik.http.middlewares.pesto_rce-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.pesto_rce-header.headers.frameDeny=true"
      - "traefik.http.middlewares.pesto_rce-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.pesto_rce-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.pesto_rce-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.pesto_rce-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.pesto_rce-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.pesto_rce-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.pesto_rce-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.pesto_rce-redirectscheme.redirectscheme.permanent=true"
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    healthcheck:
      test: "curl -f http://localhost:50051/healthz || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 4GB
          cpus: '2'
        reservations:
          memory: 100MB
          cpus: '0.10'
    networks:
      - public-web
      - pesto-internal

  pesto-registration:
    image: ghcr.io/teknologi-umum/pesto-registration:edge
    environment:
      <<: [ *defaults ]
      PORT: "80"
      SENTRY_DSN: ${REGISTRATION_SENTRY_DSN}
      Sentry__Dsn: ${REGISTRATION_SENTRY_DSN}
      Sentry__Debug: false
      Sentry__Environment: production
      RedisUrl: "db:6379"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-web"
      - "traefik.http.routers.pesto_registration.entrypoints=web,websecure"
      - "traefik.http.routers.pesto_registration.rule=Host(`pesto.teknologiumum.com`) && Path(`/api/register`)"
      - "traefik.http.routers.pesto_registration.priority=5"
      - "traefik.http.routers.pesto_registration.tls.certresolver=tlsresolver"
      - "traefik.http.routers.pesto_registration.middlewares=pesto_registration-error,pesto_registration-header,pesto_registration-rate,pesto_registration-redirectscheme,pesto_registration-inflightreq"
      - "traefik.http.services.pesto_registration.loadbalancer.server.port=80"
      - "traefik.http.services.pesto_registration.loadbalancer.server.scheme=http"
      - "traefik.http.services.pesto_registration.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.pesto_registration.loadbalancer.healthcheck.path=/healthz"
      - "traefik.http.middlewares.pesto_registration-error.errors.status=500-599"
      - "traefik.http.middlewares.pesto_registration-error.errors.service=pesto_landing@docker"
      - "traefik.http.middlewares.pesto_registration-error.errors.query=/500"
      - "traefik.http.middlewares.pesto_registration-rate.ratelimit.average=100"
      - "traefik.http.middlewares.pesto_registration-rate.ratelimit.burst=10"
      - "traefik.http.middlewares.pesto_registration-rate.ratelimit.period=1m"
      - "traefik.http.middlewares.pesto_registration-header.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.pesto_registration-header.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.pesto_registration-header.headers.accesscontrolmaxage=604800"
      - "traefik.http.middlewares.pesto_registration-header.headers.addvaryheader=true"
      - "traefik.http.middlewares.pesto_registration-header.headers.frameDeny=true"
      - "traefik.http.middlewares.pesto_registration-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.pesto_registration-header.headers.stsSeconds=604800"
      - "traefik.http.middlewares.pesto_registration-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.pesto_registration-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.pesto_registration-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.pesto_registration-header.headers.customResponseHeaders.server=Teknologi Umum"
      - "traefik.http.middlewares.pesto_registration-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.pesto_registration-redirectscheme.redirectscheme.permanent=true"
      - "traefik.http.middlewares.pesto_registration-inflightreq.inflightreq.amount=50"
      - "com.centurylinklabs.watchtower.enable=true"
    platform: linux/amd64
    healthcheck:
      test: "curl -f http://localhost:80/healthz || exit 1"
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 2GB
          cpus: '1'
        reservations:
          memory: 25MB
          cpus: '0.10'
    networks:
      - pesto-internal
      - public-web

networks:
  pesto-internal:
    external: false

  public-web:
    external: true
