name: Secret Scan

on:
  push:
  pull_request:

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/documentation@v7
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          ENABLE: EDITORCONFIG
          FILTER_REGEX_EXCLUDE: (LICENSE|CODE_OF_CONDUCT\.md|.idea)
  
  trufflehog:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
